### PR TITLE
Adding Move On Sui Semgrep grammer

### PR DESCRIPTION
**Pull request by maxmysten**
### Checklist

- [ ] Any new parsing code was already published, integrated, and merged into Semgrep. DO NOT MERGE THIS PR BEFORE THE SEMGREP INTEGRATION WORK WAS COMPLETED.
- [X ] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by nmote** [comment]
Could you share some context on this language? How similar is it to Move on Aptos?

**Review by aryx — APPROVED** [review]
@nmote move on aptos is a fork of move on sui (more or less).

**Comment by aryx** [comment]
@maxmysten FYI I get this on ./test-lang move-on-sui:
```
...
Warning: unnecessary conflicts
  `module_access`, `typed_metavariable`
  `annotation_expr`, `module_access`
  `annotation_expression`, `typed_metavariable`
  `module_access`, `variable_identifier`

```

**Comment by aryx** [comment]
@maxmysten I've pushed a new semgrep-move-on-sui. You can then use that from the semgrep repo.

**Pull request merged**
